# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest pandas scikit-learn fastapi httpx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 fast-api-c3-starter-code/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 fast-api-c3-starter-code/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # Run black cheker. The GitHub editor is 127 chars wide
        black fast-api-c3-starter-code/ --check -l 127
    - name: Run server in background
      run: uvicorn main:app &
    - name: Test with pytest
      run: |
        cd fast-api-c3-starter-code/starter/ && pytest -vv
